language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - "sudo apt-get install gfortran"
  - "pip install ."
  - "python -c 'import numpy; print(numpy.__path__)'"
script:
  - "python -c 'import numpy; print(numpy.__path__)'"
  - "cd examples ; make test"
notifications:
  email:
    - james.kermode@gmail.com
