language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - "sudo apt-get install gfortran"
  - "pip install -U numpy"
  - "pip install ."
script:
  - "cd examples ; make test"
notifications:
  email:
    - james.kermode@gmail.com
