name: Build wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v1.11.1.post1
        env:
           CIBW_SKIP: cp27-* cp35-*
           CIBW_BEFORE_ALL_MACOS: "brew link gfortran; which gfortran"
           CIBW_BEFORE_ALL_LINUX: "yum install -y gcc-gfortran"
           CIBW_BEFORE_BUILD: pip install oldest-supported-numpy
           CIBW_ENVIRONMENT: "F90=gfortran F90FLAGS=-fPIC PATH=/usr/local/bin:${PATH"
           CIBW_TEST_COMMAND: "cd ${project}/examples; make test"

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
