name: Build wheels

on: [push, pull_request, workflow_dispatch]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.9.0

      - name: Build wheels
        run: |
             if [ "$RUNNER_OS" == "Linux" ]; then
                ARCHS=auto64
             elif [ "$RUNNER_OS" == "macOS" ]; then
                ARCHS="arm64 x86_64"
             else
               echo "RUNNER_OS=$RUNNER_OS not supported!"
               exit 1
             fi
             echo "RUNNER_OS=$RUNNER_OS"
             echo "ARCHS=${ARCHS}"

             for ARCH in $ARCHS; do
                echo "ARCH=${ARCH}"
                export CIBW_ENVIRONMENT="ARCH=${ARCH} RUNNER_OS=${RUNNER_OS}"
                python -m cibuildwheel --output-dir wheelhouse --archs $ARCH
             done
        env:
           CIBW_SKIP: cp27-* cp35-* cp36-
           CIBW_ARCHS_LINUX: "auto64"
           CIBW_ARCHS_MACOS: "x86_64 arm64"           
           CIBW_BEFORE_ALL_MACOS: "ln -s $(which gfortran-10) /usr/local/bin/gfortran"
           CIBW_BEFORE_ALL_LINUX: "yum install -y gcc-gfortran"
           CIBW_BEFORE_BUILD: "bash .github/workflows/prepare-build.sh"
           CIBW_TEST_COMMAND: "cd {project}/examples; make clean; make test"
           
      # Uncomment to get SSH access for testing
      - name: Setup tmate session
        if: failure()
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 15

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
